# Generated by Django 5.2 on 2026-05-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsmod',
            name='aptitude',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='front_photo',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='side_photo',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='size',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='size_photo',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='petsmod',
            name='vermifuge',
        ),
        migrations.AddField(
            model_name='petsmod',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petsmod',
            name='arrival',
            field=models.CharField(choices=[('DE', 'Devolução'), ('IN', 'Indefinida'), ('NS', 'Nascimento'), ('RS', 'Resgate'), ('RC', 'Resgate CED')], default='RS', max_length=20),
        ),
        migrations.AddField(
            model_name='petsmod',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petsmod',
            name='chip',
            field=models.CharField(blank=True, default='Sem Chip', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='petsmod',
            name='history',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='petsmod',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/photos/front/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='petsmod',
            name='placement',
            field=models.CharField(choices=[('IN', 'Indefinido'), ('AB', 'Abrigo'), ('GI', 'Gatil Infantil'), ('GA', 'Gatil Adulto'), ('CI', 'Canil Infantil'), ('CA', 'Canil Adulto'), ('MI', 'Mirim'), ('LT', 'Lar Temporário'), ('LC', 'Lar Temporário CED'), ('TL', 'Trasladada')], default='AB', max_length=20),
        ),
        migrations.AddField(
            model_name='petsmod',
            name='species',
            field=models.CharField(choices=[('C', 'Cão'), ('G', 'Gato')], default='C', max_length=10),
        ),
        migrations.AddField(
            model_name='petsmod',
            name='status',
            field=models.CharField(choices=[('AP', 'Apto'), ('IN', 'Inapto'), ('PR', 'Em preparo'), ('AD', 'Adotado'), ('DV', 'Devolvido'), ('ES', 'Estrelinha')], default='PR', max_length=20),
        ),
        migrations.AlterField(
            model_name='petsmod',
            name='id_pet',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petsmod',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indefinido')], default='I', max_length=10),
        ),
    ]
