# Generated by Django 5.2 on 2026-05-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_petsmod_aptitude_remove_petsmod_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaleventmod',
            name='event',
        ),
    ]
