# Generated by Django 5.2 on 2026-05-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_medicaleventmod_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaleventmod',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicaleventmod',
            name='event',
            field=models.CharField(choices=[('CA', 'Castração'), ('CI', 'Cirurgia'), ('CO', 'Consulta'), ('EX', 'Exame'), ('TR', 'Tratamento'), ('VA', 'Vacinação'), ('OU', 'Outros')], default='CO', max_length=255),
        ),
    ]
