# Generated by Django 5.2 on 2026-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_medicaleventmod_details_medicaleventmod_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsmod',
            name='arrival',
            field=models.CharField(choices=[('Devolucao', 'DEVOLUÇÃO'), ('Indefinida', 'INDEFINIDA'), ('Nascimento', 'NASCIMENTO'), ('Resgate', 'RESGATE'), ('Resgate CED', 'RESGATE CED')], default='RS', max_length=20),
        ),
        migrations.AlterField(
            model_name='petsmod',
            name='placement',
            field=models.CharField(choices=[('Indefinido', 'INDEFINIDO'), ('Abrigo', 'ABRIGO'), ('Gatil Infantil', 'GATIL INFANTIL'), ('Gatil Adulto', 'GATIL ADULTO'), ('Canil Infantil', 'CANIL INFANTIL'), ('Canil Adulto', 'CANIL ADULTO'), ('Mirim', 'MIRIM'), ('Lar Temporario', 'LAR TEMPORÁRIO'), ('Lar Temporario CED', 'LAR TEMPORÁRIO CED'), ('Trasladada', 'TRASLADADA')], default='AB', max_length=20),
        ),
        migrations.AlterField(
            model_name='petsmod',
            name='sex',
            field=models.CharField(choices=[('Macho', 'MACHO'), ('Femea', 'FÊMEA'), ('Indefinido', 'INDEFINIDO')], default='I', max_length=10),
        ),
        migrations.AlterField(
            model_name='petsmod',
            name='species',
            field=models.CharField(choices=[('Cão', 'CÃO'), ('Gato', 'GATO')], default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='petsmod',
            name='status',
            field=models.CharField(choices=[('Apto', 'APTO'), ('Inapto', 'INAPTO'), ('Em Preparo', 'EM PREPARO'), ('Adotado', 'ADOTADO'), ('Devolvido', 'DEVOLVIDO'), ('Estrelinha', 'ESTRELINHA')], default='PR', max_length=20),
        ),
    ]
