# Generated by Django 5.2 on 2026-03-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheltersMod',
            fields=[
                ('id_shelter', models.AutoField(db_column='id_shelter', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('options', models.JSONField(blank=True, db_column='options', default=dict, null=True)),
            ],
        ),
    ]
