# Generated by Django 5.2 on 2026-03-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheltersmod',
            name='logo',
            field=models.ImageField(blank=True, db_column='logo', null=True, upload_to='shelters/img/logos'),
        ),
    ]
