# Generated by Django 5.2 on 2026-03-28 16:24

import shelters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_sheltersmod_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheltersmod',
            name='logo',
            field=models.ImageField(blank=True, db_column='logo', null=True, upload_to=shelters.models.shelter_logo_upload_to),
        ),
    ]
