# Generated by Django 5.2 on 2026-05-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0004_medicaleventmod_details_medicaleventmod_event'),
        ('pharma', '0005_alter_catalogmod_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEventMod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('healthcare_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('change_status', models.BooleanField(blank=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_medicos', to='pets.petsmod')),
            ],
            options={
                'verbose_name': 'Registro de Eventos Médicos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExamMod',
            fields=[
                ('medicaleventmod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medical.medicaleventmod')),
                ('positive', models.BooleanField(default=False)),
                ('report', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de Exames',
            },
            bases=('medical.medicaleventmod',),
        ),
        migrations.CreateModel(
            name='VaccineMod',
            fields=[
                ('medicaleventmod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medical.medicaleventmod')),
                ('batch', models.CharField(blank=True, max_length=50)),
                ('next_dose', models.DateField(blank=True)),
            ],
            bases=('medical.medicaleventmod',),
        ),
        migrations.CreateModel(
            name='ProcedCatalogMod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CIRUGIA', 'Cirurgia'), ('EXAME', 'Exame'), ('MEDICAÇÃO', 'Medicação'), ('TERAPIA', 'Terapia'), ('VACINA', 'Vacina')], max_length=20)),
                ('species', models.CharField(choices=[('GATO', 'Gato'), ('CÃO', 'Cão')], max_length=10)),
                ('min_application', models.IntegerField(default=1)),
                ('min_interval', models.IntegerField(blank=True, null=True)),
                ('repetition', models.IntegerField(blank=True, null=True)),
                ('mandatory', models.BooleanField(default=False)),
                ('alternatives', models.JSONField(blank=True, default=list, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Procedimento',
                'verbose_name_plural': 'Catálogo de Procedimentos',
                'constraints': [models.UniqueConstraint(fields=('name', 'type', 'species'), name='unique_catalog_procedure')],
            },
        ),
        migrations.AddField(
            model_name='medicaleventmod',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_realizados', to='medical.procedcatalogmod'),
        ),
        migrations.CreateModel(
            name='MedicationMod',
            fields=[
                ('medicaleventmod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medical.medicaleventmod')),
                ('dosage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharma.catalogmod')),
            ],
            bases=('medical.medicaleventmod',),
        ),
    ]
