# Generated by Django 5.2 on 2026-05-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinemod',
            name='next_dose',
            field=models.DateField(blank=True, null=True),
        ),
    ]
