# Generated by Django 5.2 on 2026-05-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_vaccinemod_next_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedcatalogmod',
            name='type',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('CIRUGIA', 'Cirurgia'), ('EXAME', 'Exame'), ('TERAPIA', 'Terapia'), ('TRATAMENTO', 'Tratamento'), ('VACINA', 'Vacina')], max_length=20),
        ),
    ]
