# Generated by Django 5.2 on 2026-05-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_procedcatalogmod_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedcatalogmod',
            name='type',
            field=models.CharField(choices=[('AVALIAÇÃO', 'Avaliação Médico-Veterinária'), ('CIRUGIA', 'Cirurgia'), ('EXAME', 'Exame Laboratorial'), ('TERAPIA', 'Terapia'), ('TRATAMENTO', 'Tratamento'), ('VACINA', 'Vacina')], max_length=40),
        ),
    ]
