# Generated by Django 5.2 on 2026-05-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_procedcatalogmod_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedcatalogmod',
            name='species',
            field=models.CharField(choices=[('Gato', '---GATO---'), ('Cão', '---CÃO---')], max_length=10),
        ),
        migrations.AlterField(
            model_name='procedcatalogmod',
            name='type',
            field=models.CharField(choices=[('Avaliação Médico-Veterinária', '---AVALIAÇÃO MÉDICO-VETERINÁRIA---'), ('Cirurgia', '---CIRURGIA---'), ('Exame Laboratorial', '---EXAME LABORATORIAL---'), ('Terapia', '---TERAPIA---'), ('Tratamento', '---TRATAMENTO---'), ('Vacina', '---VACINA---')], max_length=40),
        ),
    ]
