# Generated by Django 5.2 on 2026-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_alter_procedcatalogmod_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedcatalogmod',
            name='species',
            field=models.CharField(choices=[('Gato', 'Gato'), ('Cão', 'Cão')], max_length=10),
        ),
        migrations.AlterField(
            model_name='procedcatalogmod',
            name='type',
            field=models.CharField(choices=[('Avaliação Médico-Veterinária', 'Avaliação Médico-Veterinária'), ('Cirurgia', 'Cirurgia'), ('Exame Laboratorial', 'Exame Laboratorial'), ('Terapia', 'Terapia'), ('Tratamento', 'Tratamento'), ('Vacina', 'Vacina')], max_length=40),
        ),
    ]
