# Generated by Django 5.2 on 2026-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_alter_procedcatalogmod_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammod',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='laudos_exames/', verbose_name='Laudo / Resultado (PDF)'),
        ),
        migrations.AlterField(
            model_name='procedcatalogmod',
            name='type',
            field=models.CharField(choices=[('Avaliação Médico-Veterinária', 'Avaliação Médico-Veterinária'), ('Cirurgia', 'Cirurgia'), ('Exame', 'Exame'), ('Terapia', 'Terapia'), ('Tratamento', 'Tratamento'), ('Vacina', 'Vacina')], max_length=40),
        ),
    ]
