# Generated by Django 5.2 on 2026-04-26 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmGroupMod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('allowed_units', models.JSONField(blank=True, default=list, null=True)),
                ('help_text', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmPresentMod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('dispensing_unit', models.CharField(max_length=20)),
                ('control_type', models.CharField(choices=[('NUM', 'Numérico'), ('NIV', 'Nível'), ('USO', 'Uso')], default='NIV', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default='LIQUIDO', on_delete=django.db.models.deletion.SET_DEFAULT, to='pharma.pharmgroupmod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogMod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('primary_name', models.CharField(max_length=100, null=True)),
                ('concentration_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('concentration_unity', models.CharField(max_length=10)),
                ('assoc_concentration', models.BooleanField(default=False)),
                ('animal_weight_conc', models.BooleanField(default=False)),
                ('spec_concentration', models.JSONField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('MED', 'Medicamento'), ('SUP', 'Suplemento'), ('INS', 'Insumo'), ('DIS', 'Dispositivo'), ('COS', 'Cosmético')], default='MED', max_length=10)),
                ('min_stock', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharma.pharmpresentmod')),
            ],
            options={
                'verbose_name': 'Definição de produto',
                'verbose_name_plural': 'Catálogo de Produtos',
            },
        ),
        migrations.CreateModel(
            name='StockMod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('secondary_name', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('stocking_unity', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('sku_qty', models.IntegerField(default=1)),
                ('dosage_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='pharma.catalogmod')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='catalogmod',
            constraint=models.UniqueConstraint(fields=('primary_name', 'concentration_value', 'concentration_unity', 'presentation'), name='unique_catalog_item'),
        ),
    ]
