# Generated by Django 5.2 on 2026-04-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmpresentmod',
            name='control_type',
            field=models.CharField(choices=[('NUM', 'Numérico'), ('NIV', 'Nível'), ('USO', 'Uso')], default='NIV', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmpresentmod',
            name='dispensing_unit',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pharmpresentmod',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
