# Generated by Django 5.2 on 2026-05-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0002_alter_pharmpresentmod_control_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmod',
            name='animal_weight_conc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='catalogmod',
            name='assoc_concentration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='catalogmod',
            name='concentration_unity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalogmod',
            name='item_type',
            field=models.CharField(blank=True, choices=[('MED', 'Medicamento'), ('SUP', 'Suplemento'), ('INS', 'Insumo'), ('DIS', 'Dispositivo'), ('COS', 'Cosmético')], default='MED', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalogmod',
            name='spec_concentration',
            field=models.JSONField(blank=True, default=False, null=True),
        ),
    ]
