# Generated by Django 5.2 on 2026-05-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0003_alter_catalogmod_animal_weight_conc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmod',
            name='sku_qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
