# Generated by Django 5.2 on 2026-05-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_alter_stockmod_sku_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmod',
            name='item_type',
            field=models.CharField(choices=[('MED', 'Medicamento'), ('SUP', 'Suplemento'), ('INS', 'Insumo'), ('DIS', 'Dispositivo'), ('COS', 'Cosmético')], default='MED', max_length=10),
        ),
        migrations.AlterField(
            model_name='catalogmod',
            name='spec_concentration',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
